<?php
/**
 * Form to PDF Generator Class
 */

// Exit if accessed directly
if (!defined('ABSPATH')) {
    exit;
}

class Form_To_PDF {
    private static $instance = null;
    
    /**
     * Get singleton instance
     */
    public static function get_instance() {
        if (null === self::$instance) {
            self::$instance = new self();
        }
        return self::$instance;
    }
    
    /**
     * Constructor
     */
    public function __construct() {
        // Load dependencies
        require_once dirname(__FILE__) . '/class-form-renderer.php';
        require_once dirname(__FILE__) . '/class-form-processor.php';
        
        // Register shortcode
        add_shortcode('pdf_form', array($this, 'render_form_shortcode'));
        
        // AJAX handlers
        add_action('wp_ajax_process_pdf_form', array($this, 'process_pdf_form'));
        add_action('wp_ajax_nopriv_process_pdf_form', array($this, 'process_pdf_form'));
        
        // Enqueue scripts and styles
        add_action('wp_enqueue_scripts', array($this, 'enqueue_scripts'));
    }
    
    /**
     * Enqueue necessary scripts and styles
     */
    public function enqueue_scripts() {
        wp_enqueue_style(
            'form-to-pdf-style',
            CSV_TO_PDF_URL . 'assets/css/form-to-pdf.css',
            array(),
            CSV_TO_PDF_VERSION
        );
        
        wp_enqueue_script(
            'form-to-pdf-script',
            CSV_TO_PDF_URL . 'assets/js/form-to-pdf.js',
            array('jquery'),
            CSV_TO_PDF_VERSION,
            true
        );
        
        wp_localize_script('form-to-pdf-script', 'pdf_form_vars', array(
            'ajax_url' => admin_url('admin-ajax.php'),
            'nonce' => wp_create_nonce('pdf_form_nonce')
        ));
    }
    
    /**
     * Render form shortcode
     */
    public function render_form_shortcode($atts) {
        $atts = shortcode_atts(array(
            'form' => '', // Form template ID
            'pdf_template' => '', // PDF template ID
            'title' => 'PDF Form',
        ), $atts, 'pdf_form');
        
        // Both form and PDF template are required
        if (empty($atts['form']) || empty($atts['pdf_template'])) {
            return '<div class="pdf-form-error">Error: Both form and pdf_template attributes are required.</div>';
        }
        
        // Initialize form renderer
        $form_renderer = new Form_Renderer();
        
        // Return the rendered form
        return $form_renderer->render_form($atts['form'], $atts['pdf_template'], $atts);
    }
    
    /**
     * Process PDF form submission (AJAX handler)
     */
    public function process_pdf_form() {
        // Check nonce
        if (!isset($_POST['nonce']) || !wp_verify_nonce($_POST['nonce'], 'pdf_form_nonce')) {
            wp_send_json_error('Security check failed');
            return;
        }
        
        $form_id = isset($_POST['form_id']) ? sanitize_text_field($_POST['form_id']) : '';
        $pdf_template = isset($_POST['pdf_template']) ? sanitize_text_field($_POST['pdf_template']) : '';
        
        if (empty($form_id) || empty($pdf_template)) {
            wp_send_json_error('Missing required parameters');
            return;
        }
        
        // Initialize form processor
        $processor = new Form_Processor();
        
        try {
            // Get user data
            $user_data = get_pdf_form_user_data();
            
            // Process the form data and generate PDF
            $result = $processor->process_form($_POST, $pdf_template);
            
            // Return success response with download URL
            wp_send_json_success(array(
                'download_url' => $result['download_url'],
                'message' => __('Your PDF has been generated successfully!', 'csv-to-pdf-generator'),
                'user_info' => 'Generated by ' . $user_data['username'] . ' on ' . $user_data['datetime']
            ));
        } catch (Exception $e) {
            wp_send_json_error($e->getMessage());
        }
        
        wp_die();
    }
}